remote_theme: gustavoquinalha/jekyll-help-center-theme

title: "noice.link help center"
description: "Need help with noice.link? This is the place for you!"
author: "noice.link"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
